version: "3.4"

services:
  db_test:
    image: postgres:11.5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

  sinatra:
    env_file:
      - test.env
    build:
      context: .
      target: test
    ports:
      - "9292:9292"
    volumes:
      - .:/app
    depends_on:
      - db_test
    networks:
      - local

volumes:
  .:
  postgres_test_data:

networks:
  local:

