version: "3.4"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local

  sinatra:
    env_file:
      - .env
    build: .
    ports:
      - "9292:9292"
    volumes:
      - .:/app
    depends_on:
      - db_postgres
    networks:
      - local

volumes:
  .:
  postgres_data:

networks:
  local:

